[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deepface>=0.0.93",
    "numpy>=2.2.3",
    "opencv-python-headless>=4.11.0.86",
]
