[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deepface==0.0.79",
    "numpy==1.24.3",
    "opencv-python-headless==4.8.0.74",
    "tensorflow==2.13.0",
]
